### ISSUE TITLE
change code name?

### ISSUE THREAD

**Issue by bwheelz36** [ACRF-Image-X-Institute/mri_distortion_toolkit#139]
I think we should change this to 'mri_distortion_toolkit' or something - thoughts/ objections?

**Comment by paulzyliu** [comment]
Sounds good to me.. the actual image correction part is going to be a separate repo now?

**Comment by bwheelz36** [comment]
I think we leave it in this one, what do you think?

**Comment by bwheelz36** [comment]
- [ ] update pypi release package with new name
- [ ] update readme with new name

**Comment by paulzyliu** [comment]
I think that's fine.. I just saw a separate distortion correction git on the repo and thought you were going to move it

**Comment by bwheelz36** [comment]
- [ ] rename module
